export const GuardStatus = Object.freeze({
  STANDBY: 'STANDBY',
  ACTIVE_GUARD: 'ACTIVE_GUARD',
  NOT_WORN: 'NOT_WORN',
  REST_PAUSED: 'REST_PAUSED',
  AWAITING_CONFIRMATION: 'AWAITING_CONFIRMATION',
  LOCAL_ALARM: 'LOCAL_ALARM',
})

export const InputType = Object.freeze({
  TICK: 'TICK',
  STEP_CHANGED: 'STEP_CHANGED',
  DISTANCE_CHANGED: 'DISTANCE_CHANGED',
  HEART_RATE_SAMPLE: 'HEART_RATE_SAMPLE',
  WEAR_CHANGED: 'WEAR_CHANGED',
  PHONE_CONNECTION_CHANGED: 'PHONE_CONNECTION_CHANGED',
  ESCALATION_ALARM_FIRED: 'ESCALATION_ALARM_FIRED',
  USER_SAFE_REQUESTED: 'USER_SAFE_REQUESTED',
  USER_SAFE_CONFIRMED: 'USER_SAFE_CONFIRMED',
  USER_REST_REQUESTED: 'USER_REST_REQUESTED',
  USER_HELP_REQUESTED: 'USER_HELP_REQUESTED',
  USER_HELP_NOW: 'USER_HELP_NOW',
  USER_RESOLVED: 'USER_RESOLVED',
})

export const EffectType = Object.freeze({
  VIBRATE_GENTLE: 'VIBRATE_GENTLE',
  VIBRATE_URGENT: 'VIBRATE_URGENT',
  NOTIFY_INTENSITY: 'NOTIFY_INTENSITY',
  NOTIFY_CONFIRMATION: 'NOTIFY_CONFIRMATION',
  NOTIFY_GUARD_PAUSED: 'NOTIFY_GUARD_PAUSED',
  SCHEDULE_ESCALATION_ALARM: 'SCHEDULE_ESCALATION_ALARM',
  CANCEL_ESCALATION_ALARM: 'CANCEL_ESCALATION_ALARM',
  QUEUE_HELP_REQUEST: 'QUEUE_HELP_REQUEST',
  QUEUE_RESOLUTION: 'QUEUE_RESOLUTION',
  START_LOCAL_ALARM: 'START_LOCAL_ALARM',
  STOP_LOCAL_ALARM: 'STOP_LOCAL_ALARM',
  LOG_EVENT: 'LOG_EVENT',
})
